UniCare/Areas/Admin/Pages/ApplicationPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;
using UniCare.Data.Model;

namespace UniCare.Areas.Admin.Pages.ApplicationPage
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Admin")]

    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public DetailsModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Application Application { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Applications == null)
            {
                return NotFound();
            }

            var application = await _context.Applications
                .Include(x=>x.Qualifications)
                .Include(x=>x.EmploymentHistories)
                .Include(x=>x.ApplicationReferences)
                .Include(x=>x.OccupationalHealthAssessments)
                .Include(x=>x.Vacination)
                .Include(x=>x.HealthQualifications)
                .Include(x=>x.Documents)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (application == null)
            {
                return NotFound();
            }
            else 
            {
                Application = application;
            }
            return Page();
        }
    }
}

UniCare/Areas/Admin/Pages/AppointmentPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;
using UniCare.Data.Model;

namespace UniCare.Areas.Admin.Pages.AppointmentPage
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Admin")]

    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public DetailsModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Appointment Appointment { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Appointments == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments.FirstOrDefaultAsync(m => m.Id == id);
            if (appointment == null)
            {
                return NotFound();
            }
            else 
            {
                Appointment = appointment;
            }
            return Page();
        }
    }
}

UniCare/Areas/Admin/Pages/Dashboard/Index.cshtml.cs
using UniCare.Data.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace UniCare.Areas.Admin.Pages.Dashboard
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Admin")]

    public class IndexModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public IndexModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

        public int Appointment { get; set; } 
        public int Application { get; set; }
        public int User { get; set; }

        public async Task OnGetAsync()
        {
             
                Appointment = await _context.Appointments.CountAsync();
            Application = await _context.Applications.CountAsync();
            User = await _context.Users.Where(x => x.Email != "admin@unicare.co").CountAsync();
             
        }
    }
}

UniCare/Areas/Admin/Pages/HealthCareQualificationPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;
using UniCare.Data.Model;

namespace UniCare.Areas.Admin.Pages.HealthCareQualificationPage
{
    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public DetailsModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public HealthQualification HealthQualification { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.HealthQualifications == null)
            {
                return NotFound();
            }

            var healthqualification = await _context.HealthQualifications.FirstOrDefaultAsync(m => m.Id == id);
            if (healthqualification == null)
            {
                return NotFound();
            }
            else 
            {
                HealthQualification = healthqualification;
            }
            return Page();
        }
    }
}

UniCare/Areas/Admin/Pages/MessagesPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;
using UniCare.Data.Model;

namespace UniCare.Areas.Admin.Pages.MessagesPage
{
    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public DetailsModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Message Message { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Messages == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.FirstOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }
            else 
            {
                Message = message;
            }
            return Page();
        }
    }
}

UniCare/Areas/Admin/Pages/NewsBlogPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;
using UniCare.Data.Model;

namespace UniCare.Areas.Admin.Pages.NewsBlogPage
{
    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public DetailsModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public NewsBlog NewsBlog { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.NewsBlogs == null)
            {
                return NotFound();
            }

            var newsblog = await _context.NewsBlogs.FirstOrDefaultAsync(m => m.Id == id);
            if (newsblog == null)
            {
                return NotFound();
            }
            else 
            {
                NewsBlog = newsblog;
            }
            return Page();
        }
    }
}

UniCare/Areas/Admin/Pages/QualificationPageList/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;
using UniCare.Data.Model;

namespace UniCare.Areas.Admin.Pages.QualificationPageList
{
    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public DetailsModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public Qualification Qualification { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Qualifications == null)
            {
                return NotFound();
            }

            var qualification = await _context.Qualifications.FirstOrDefaultAsync(m => m.Id == id);
            if (qualification == null)
            {
                return NotFound();
            }
            else 
            {
                Qualification = qualification;
            }
            return Page();
        }
    }
}

UniCare/Areas/Admin/Pages/TimeSheetPage/SD/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;

namespace UniCare.Areas.Admin.Pages.TimeSheetPage.SD
{
    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;

        public DetailsModel(UniCare.Data.ApplicationDbContext context)
        {
            _context = context;
        }

      public UserTimeSheet UserTimeSheet { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.UserTimeSheets == null)
            {
                return NotFound();
            }

            var usertimesheet = await _context.UserTimeSheets.FirstOrDefaultAsync(m => m.Id == id);
            if (usertimesheet == null)
            {
                return NotFound();
            }
            else 
            {
                UserTimeSheet = usertimesheet;
            }
            return Page();
        }
    }
}

UniCare/Areas/Admin/Pages/Users/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using UniCare.Data;
using UniCare.Data.Model;
using Microsoft.AspNetCore.Identity;

namespace UniCare.Areas.Admin.Pages.Users
{
    [Microsoft.AspNetCore.Authorization.Authorize(Roles = "Admin")]

    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;
        private readonly UserManager<Profile> _userManager;

        public DetailsModel(UniCare.Data.ApplicationDbContext context, UserManager<Profile> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public Profile AppUser { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appuser = await _userManager.Users.FirstOrDefaultAsync(m => m.Id == id);
            if (appuser == null)
            {
                return NotFound();
            }
            else 
            {
                AppUser = appuser;
            }
            return Page();
        }
    }
}

UniCare/Areas/Staff/Pages/Dashboard/Details.cshtml.cs
using UniCare.Data;
using UniCare.Data.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using static UniCare.Data.Model.Enum;
using System.Net.Mail;

namespace UniCare.Areas.Staff.Pages.Dashboard
{
    [Authorize]

    public class DetailsModel : PageModel
    {
        private readonly UniCare.Data.ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnv;

        public DetailsModel(UniCare.Data.ApplicationDbContext context, IWebHostEnvironment hostingEnv)
        {
            _context = context;
            _hostingEnv = hostingEnv;
        }
        [BindProperty]
        public UserTimeSheet UserTimeSheet { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.UserTimeSheets == null)
            {
                return NotFound();
            }

            var usertimesheet = await _context.UserTimeSheets
                .Include(x=>x.TimeSheet)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usertimesheet == null)
            {
                return RedirectToPage("./TimeSheet");
            }
            else
            {
                UserTimeSheet = usertimesheet;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostStartAsync()
        {

            var usertimesheet = await _context.UserTimeSheets
                .Include(x=>x.User)
                .FirstOrDefaultAsync(m => m.Id == UserTimeSheet.Id);
            usertimesheet.UserSheetStartTime = DateTime.UtcNow; 
            _context.Attach(usertimesheet).State = EntityState.Modified;


            await _context.SaveChangesAsync();
            TempData["success"] = "Successful";


            //send email
            string title = "TimeSheet Start Time Update";
            string msg = $"{usertimesheet.User.Surname + usertimesheet.User.FirstName} started the sheet at {usertimesheet.UserSheetStartTime} at {usertimesheet.PostCode}";

            try
            {
                //email
                StreamReader sr = new StreamReader(System.IO.Path.Combine(_hostingEnv.WebRootPath, "Mail.html"));
                //create the mail message 
                MailMessage mail = new MailMessage();

                string mailmsg = sr.ReadToEnd();
                mailmsg = mailmsg.Replace("{title}", title);
                mailmsg = mailmsg.Replace("{MESSAGE}", msg);
                mailmsg = mailmsg.Replace("{name}", "Admin");
                mail.Body = mailmsg;
                sr.Close();
                MailSystem ms = new MailSystem();
                ms.Email = "info@chosenhealthcare.co.uk";
                ms.Title = title;
                ms.Mail = mailmsg;
                ms.Retries = 0; ms.NotificationType = NotificationType.Email;
                ms.NotificationStatus = NotificationStatus.NotSent;
                _context.MailSystems.Add(ms);
                await _context.SaveChangesAsync();

            }
            catch (Exception)
            {

            }

            try
            {
                //sms

                MailSystem ms = new MailSystem();
                ms.Email = "+447852528020";
                ms.Title = title;
                ms.Mail = msg;
                ms.Retries = 0; ms.NotificationType = NotificationType.SMS;
                ms.NotificationStatus = NotificationStatus.NotSent;
                _context.MailSystems.Add(ms);
                await _context.SaveChangesAsync();

            }
            catch (Exception)
            {

            }


            return RedirectToPage("./Details", new { id = usertimesheet.Id });
        }

        public async Task<IActionResult> OnPostEndAsync()
        {

            var usertimesheet = await _context.UserTimeSheets.Include(x => x.User).FirstOrDefaultAsync(m => m.Id == UserTimeSheet.Id);
            usertimesheet.UserSheetEndTime = DateTime.UtcNow;
            _context.Attach(usertimesheet).State = EntityState.Modified;


            await _context.SaveChangesAsync();

            TempData["success"] = "Successful";


            //send email
            string title = "TimeSheet End Time Update";
            string msg = $"{usertimesheet.User.Surname + usertimesheet.User.FirstName} started the sheet at {usertimesheet.UserSheetEndTime} at {usertimesheet.PostCode}";

            try
            {
                //email
                StreamReader sr = new StreamReader(System.IO.Path.Combine(_hostingEnv.WebRootPath, "Mail.html"));
                //create the mail message 
                MailMessage mail = new MailMessage();

                string mailmsg = sr.ReadToEnd();
                mailmsg = mailmsg.Replace("{title}", title);
                mailmsg = mailmsg.Replace("{MESSAGE}", msg);
                mailmsg = mailmsg.Replace("{name}", "Admin");
                mail.Body = mailmsg;
                sr.Close();
                MailSystem ms = new MailSystem();
                ms.Email = "info@chosenhealthcare.co.uk";
                ms.Title = title;
                ms.Mail = mailmsg;
                ms.Retries = 0; ms.NotificationType = NotificationType.Email;
                ms.NotificationStatus = NotificationStatus.NotSent;
                _context.MailSystems.Add(ms);
                await _context.SaveChangesAsync();

            }
            catch (Exception)
            {

            }

            try
            {
                //sms

                MailSystem ms = new MailSystem();
                ms.Email = "+447852528020";
                ms.Title = title;
                ms.Mail = msg;
                ms.Retries = 0; ms.NotificationType = NotificationType.SMS;
                ms.NotificationStatus = NotificationStatus.NotSent;
                _context.MailSystems.Add(ms);
                await _context.SaveChangesAsync();

            }
            catch (Exception)
            {

            }


            return RedirectToPage("./Details", new { id = usertimesheet.Id });
        }
    }

}

UniCare/Areas/Staff/Pages/Dashboard/AcceptanceStatus.cshtml
@page
@model UniCare.Areas.Staff.Pages.Dashboard.AcceptanceStatusModel
@{
}
<div class="row">
    <h2>ACCEPT/DECLINE TIMESHEET</h2>
    <h4>TIME SHEET UPDATE FOR @Model.UserTimeSheet.TimeSheet.Date.ToString("ddd dd MMM, yyyy").ToUpper()</h4>

    <div class="col-md-12">
        <dl class="row">
            @if (TempData["success"] != null)
            {
                <div class="alert alert-success">
                    <strong>@TempData["success"]</strong>
                </div>

            }
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserTimeSheet.StartTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserTimeSheet.StartTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserTimeSheet.EndTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserTimeSheet.EndTime)
            </dd>

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserTimeSheet.Address)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserTimeSheet.Address)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserTimeSheet.PostCode)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserTimeSheet.PostCode)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserTimeSheet.RatePerHour)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserTimeSheet.RatePerHour)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.UserTimeSheet.Break)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.UserTimeSheet.Break)
            </dd>

        </dl>
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserTimeSheet.Id" />
            <div class="form-group">
                <label asp-for="UserTimeSheet.TimesheetAcceptance" class="control-label"></label>
                @Html.DropDownListFor(model => model.UserTimeSheet.TimesheetAcceptance, new SelectList(Enum.GetValues(typeof(UniCare.Data.Model.Enum.TimesheetAcceptance))), new { @class = "form-control" })
                <span asp-validation-for="UserTimeSheet.TimesheetAcceptance" class="text-danger"></span>
            </div>
            @if(Model.UserTimeSheet.UserId != null) { 
            <div class="form-group">
                <label asp-for="UserTimeSheet.AcceptedReason" class="control-label"></label>
                <textarea asp-for="UserTimeSheet.AcceptedReason" class="form-control"></textarea>
                <span asp-validation-for="UserTimeSheet.AcceptedReason" class="text-danger"></span>
            </div>
            }
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-success" />
                <a asp-page="./TimeSheet" class="btn btn-primary">Back to Timesheet</a>

            </div>
        </form>
    </div>
</div>

UniCare/Areas/Staff/Pages/Dashboard/Details.cshtml
@page
@model UniCare.Areas.Staff.Pages.Dashboard.DetailsModel
@{
}

<div>
    <h4>TIME SHEET DETAILS FOR @Model.UserTimeSheet.TimeSheet.Date.ToString("ddd dd MMM, yyyy").ToUpper()</h4>
    @if (TempData["success"] != null)
    {
        <div class="alert alert-success">
            <strong>@TempData["success"]</strong>
        </div>

    }

    @if (Model.UserTimeSheet.TimesheetAcceptance == UniCare.Data.Model.Enum.TimesheetAcceptance.Accepted)
    {
        <button class="btn btn-success">
            Acceptance Status:

            <span>Accepted</span>
        </button>
    }
    else if (Model.UserTimeSheet.TimesheetAcceptance == UniCare.Data.Model.Enum.TimesheetAcceptance.Declined)
    {
        <button class="btn btn-danger">
            Acceptance Status:

            <span>Declined</span>
            <span>
                <br />  @Model.UserTimeSheet.AcceptedReason
            </span>
        </button>
    }
    else if (Model.UserTimeSheet.TimesheetAcceptance == UniCare.Data.Model.Enum.TimesheetAcceptance.Canceled)
    {
        <button class="btn btn-danger">
            Acceptance Status:

            <span>Canceled</span>
            <span>
                <br /> @Model.UserTimeSheet.AcceptedReason
            </span>
        </button>
    }
    else if (Model.UserTimeSheet.TimesheetAcceptance == UniCare.Data.Model.Enum.TimesheetAcceptance.Pending)
    {
        <button class="btn btn-info">
            Acceptance Status:

            <span>Pending</span>
        </button>
    }
    @{
        // Calculate remaining hours for each item
        DateTime now = DateTime.UtcNow; // Get current time in UTC
        TimeSpan remainingTime = Model.UserTimeSheet.AcceptanceExpirationTime - now;
        int remainingHours = (int)Math.Ceiling(remainingTime.TotalHours); // Calculate remaining hours

        // Ensure remaining hours is not negative
        if (remainingHours < 0)
        {
            remainingHours = 0;
        }
        // Determine whether to display "hr" or "hrs"
        string hoursLabel = remainingHours == 1 ? "hr" : "hrs";
    }
    <h5>
        Make sure to accept or decline within the time frame.<br />
        @Html.DisplayFor(modelItem => Model.UserTimeSheet.AcceptanceExpirationTime)  (@remainingHours@hoursLabel)
    </h5>
    @if (Model.UserTimeSheet.TimesheetAcceptance == UniCare.Data.Model.Enum.TimesheetAcceptance.Accepted)
    {
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>When I started my Sheet</th>
                    <td>
                        @if (Model.UserTimeSheet.UserSheetStartTime != null)
                        {

                            @Html.DisplayFor(model => model.UserTimeSheet.UserSheetStartTime.Value)
                        }
                        else
                        {
                            <span>--/--/-- --:--</span>

                            <form method="post" asp-page-handler="Start">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="UserTimeSheet.Id" />

                                <input type="submit" value="Mark Start Time" class="btn btn-success" />

                            </form>
                        }
                    </td>
                </tr>
                <tr>
                    <th>When I close my Sheet</th>
                    <td>
                        @if (Model.UserTimeSheet.UserSheetEndTime != null)
                        {

                            @Html.DisplayFor(model => model.UserTimeSheet.UserSheetEndTime.Value)
                        }
                        else
                        {
                            <span>--/--/-- --:--</span>
                            <form method="post" asp-page-handler="End">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="UserTimeSheet.Id" />

                                <input type="submit" value="Mark End Time" class="btn btn-success" />

                            </form>
                        }
                    </td>
                </tr>
            </thead>
        </table>


    }
    <dl class="row">





        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserTimeSheet.StartTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserTimeSheet.StartTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserTimeSheet.EndTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserTimeSheet.EndTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserTimeSheet.Report)
        </dt>
        <dd class="col-sm-10">
            @Html.Raw(Model.UserTimeSheet.Report)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserTimeSheet.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserTimeSheet.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserTimeSheet.PostCode)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserTimeSheet.PostCode)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserTimeSheet.RatePerHour)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserTimeSheet.RatePerHour)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserTimeSheet.Break)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserTimeSheet.Break)
        </dd>

    </dl>
</div>
<div>

    @if (remainingHours > 0)
    {
        if (Model.UserTimeSheet.TimesheetAcceptance == UniCare.Data.Model.Enum.TimesheetAcceptance.Pending)
        {
            <a asp-page="./AcceptanceStatus" asp-route-id="@Model.UserTimeSheet?.Id" class="btn btn-info">Accept/Declined</a>
        }
    }
    @if (Model.UserTimeSheet.TimesheetAcceptance == UniCare.Data.Model.Enum.TimesheetAcceptance.Accepted)
    {
    <a asp-page="./Update" asp-route-id="@Model.UserTimeSheet?.Id" class="btn btn-primary">Update</a>
    }
    <a asp-page="./TimeSheet" class="btn btn-warning">Back to Timesheet</a>
</div>

UniCare/Areas/Staff/Pages/Dashboard/Index.cshtml
@page
@model UniCare.Areas.Staff.Pages.Dashboard.IndexModel
@{
}

<div>
    <div class="row">
        <a asp-page="/Dashboard/TimeSheet" asp-area="Staff">
            <div class="col-md-5 btn btn-primary">
                <h1>@Model.TimeSheet</h1>
                <h4>TimeSheet</h4>
            </div>
        </a>
        <a asp-page="/Dashboard/MessagePage" asp-area="Staff">
            <div class="col-md-5 btn btn-primary">
                <h1>@Model.Messages</h1>
                <h4>Messages</h4>
            </div>
        </a>
       
         
    </div>
</div>

UniCare/Areas/Staff/Pages/Dashboard/MsgDetails.cshtml
@page
@model UniCare.Areas.Staff.Pages.Dashboard.MsgDetailsModel

@{
    ViewData["Title"] = "MsgDetails";
}

<h1>Message Details</h1>

<div>

    <dl class="row">
        <dt class="col-sm-2">
            Date
        </dt>
        <dd class="col-sm-10">
            @Model.Message.Date.ToString("ddd dd MMM, yyyy")
            <br />
            @Model.Message.Date.ToString("HH:mm")
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Message.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.Raw(Model.Message.Description)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Message.Read)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Message.Read)
        </dd>
      
    </dl>
</div>
<div>
    <a asp-page="./MessagePage" class="btn btn-primary">Back to List</a>
</div>